craft_sites:
  example.com:
    site_hosts:
      - example.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@example.dev
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
