---
- name: "Craft CMS Server: Install LEMP Stack with PHP 7.0 and MariaDB MySQL"
  hosts: web:&development
  become: yes
  remote_user: vagrant

  roles:
    - { role: common, tags: [common] }
    - { role: fail2ban, tags: [fail2ban] }
    - { role: ferm, tags: [ferm] }
    - { role: ntp }
    - { role: sshd, tags: [sshd] }
    - { role: mariadb, tags: [mariadb], when: not mysql_remote_database }
    - { role: ssmtp, tags: [ssmtp mail] }
    - { role: mailhog, tags: [mailhog mail] }
    - { role: php, tags: [php] }
    - { role: nginx, tags: [nginx] }
    - { role: logrotate, tags: [logrotate] }
    - { role: composer, tags: [composer] }
    - { role: craft-cli, tags: [craft-cli] }
    - { role: craft-setup, tags: [craft, craft-setup] }
    - { role: craft-install, tags: [craft, craft-install] }
